# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Galaxy Training for Pathogen Genomics, AMR Detection & Virus ID
tagline:             IZS3
description:         Galaxy Training for Pathogen Genomics, AMR Detection & Virus ID is a hands-on course designed for biologists and bioinformaticians at Sassari University Hospital's Department of Hospital Hygiene, Epidemiology, and Infections.
url:                 'https://next-crs4.github.io/galaxy-training-bioshield'
baseurl:             ''
twitter_username:
github_username:  crs4
pages_url: https://next-crs4.github.io/galaxy-training-bioshield
github_url: https://github.com/next-crs4/galaxy-training-bioshield

# Custom vars
version:             26.01

# Build settings
markdown: kramdown
